apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task1-myapp
  template:
    metadata:
      labels:
        app: task1-myapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: task1-service-nginx
spec:
  selector:
    app: task1-myapp
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080